In [1]:
import pandas as pd

In [2]:
bmi = pd.read_csv('../bmi.csv')
bmi.head()

   Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [3]:
bmi = bmi.drop('Gender', axis=1)
bmi.head()

   Height  Weight  Index
0     174      96      4
1     189      87      2
2     185     110      4
3     195     104      3
4     149      61      3

In [4]:
# Rename for clarity
bmi = bmi.rename(columns={"Height": "X1", "Weight": "X2", "Index": "y"})
bmi.head()

    X1   X2  y
0  174   96  4
1  189   87  2
2  185  110  4
3  195  104  3
4  149   61  3

In [5]:
# Step 1: Compute necessary sums
bmi['X1_squared'] = bmi['X1'] ** 2
bmi['X2_squared'] = bmi['X2'] ** 2
bmi['X1_y'] = bmi['X1'] * bmi['y']
bmi['X2_y'] = bmi['X2'] * bmi['y']
bmi['X1_X2'] = bmi['X1'] * bmi['X2']

In [6]:
# Totals
n = len(bmi) # Subtracting 1 for the header row
sum_X1 = bmi['X1'].sum()
sum_X2 = bmi['X2'].sum()
sum_y = bmi['y'].sum()
sum_X1_squared = bmi['X1_squared'].sum()
sum_X2_squared = bmi['X2_squared'].sum()
sum_X1_y = bmi['X1_y'].sum()
sum_X2_y = bmi['X2_y'].sum()
sum_X1_X2 = bmi['X1_X2'].sum()

# Totals
print(f"n: {n}")
print(f"sum_X1: {sum_X1}")
print(f"sum_X2: {sum_X2}")
print(f"sum_y: {sum_y}")
print(f"sum_X1_squared: {sum_X1_squared}")
print(f"sum_X2_squared: {sum_X2_squared}")
print(f"sum_X1_y: {sum_X1_y}")
print(f"sum_X2_y: {sum_X2_y}")
print(f"sum_X1_X2: {sum_X1_X2}")

n: 500
sum_X1: 84972
sum_X2: 53000
sum_y: 1874
sum_X1_squared: 14574288
sum_X2_squared: 6141268
sum_X1_y: 313800
sum_X2_y: 216261
sum_X1_X2: 9007150

In [7]:
X1_bar = bmi['X1'].mean()
X2_bar = bmi['X2'].mean()
y_bar = bmi['y'].mean()

print(f"X1_bar: {X1_bar}, X2_bar: {X2_bar}, y_bar: {y_bar}")

X1_bar: 169.944, X2_bar: 106.0, y_bar: 3.748

In [8]:
# Step 2: Compute regression sums
reg_s_X1_squared = sum_X1_squared - ((sum_X1 ** 2) / n)
reg_s_X2_squared = sum_X2_squared - ((sum_X2 ** 2) / n)
reg_s_X1_y = sum_X1_y - ((sum_X1 * sum_y) / n)
reg_s_X2_y = sum_X2_y - ((sum_X2 * sum_y) / n)
reg_s_X1_X2 = sum_X1_X2 - ((sum_X1 * sum_X2) / n)

print("Regression Sums:")
print(f"reg_s_X1_squared: {reg_s_X1_squared}")
print(f"reg_s_X2_squared: {reg_s_X2_squared}")
print(f"reg_s_X1_y: {reg_s_X1_y}")
print(f"reg_s_X2_y: {reg_s_X2_y}")
print(f"reg_s_X1_X2: {reg_s_X1_X2}")

Regression Sums:
reg_s_X1_squared: 133806.43200000003
reg_s_X2_squared: 523268.0
reg_s_X1_y: -4675.055999999982
reg_s_X2_y: 17617.0
reg_s_X1_X2: 118.0

In [9]:
# Step 3: b0 and b1, b2 calculations (corrected)
b1 = ((reg_s_X2_squared * reg_s_X1_y) - (reg_s_X1_X2 * reg_s_X2_y)) / \
     ((reg_s_X1_squared * reg_s_X2_squared) - (reg_s_X1_X2 ** 2))

b2 = ((reg_s_X1_squared * reg_s_X2_y) - (reg_s_X1_X2 * reg_s_X1_y)) / \
     ((reg_s_X1_squared * reg_s_X2_squared) - (reg_s_X1_X2 ** 2))

b0 = y_bar - (b1 * X1_bar) - (b2 * X2_bar)

print(f"b0: {b0:.4f}, b1: {b1:.4f}, b2: {b2:.4f}")

b0: 6.1211, b1: -0.0350, b2: 0.0337

In [10]:
def predict_bmi_value(height, weight):
    """
    Predicts the BMI index category value using the regression coefficients.
    """
    return b0 + b1 * height + b2 * weight

def bmi_category_name(bmi_value):
    """
    Returns the BMI category name for a given predicted value.
    """
    categories = {
        0: "Extremely Weak",
        1: "Weak",
        2: "Normal",
        3: "Overweight",
        4: "Obesity",
        5: "Extreme Obesity"
    }
    rounded = int(round(bmi_value))
    return categories.get(rounded, "Unknown")

# Example usage
height = 170
weight = 65
predicted_value = predict_bmi_value(height, weight)
category = bmi_category_name(predicted_value)
print(f"Predicted BMI Value: {predicted_value:.2f}")
print(f"BMI Category: {category}")

Predicted BMI Value: 2.37
BMI Category: Normal